FROM golang:1.22-alpine AS builder
WORKDIR /src

COPY go.mod ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /mini-redis .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /mini-redis-bench ./bench

FROM alpine:3.20
WORKDIR /
COPY --from=builder /mini-redis /mini-redis
COPY --from=builder /mini-redis-bench /mini-redis-bench

EXPOSE 7379
